project:
  type: website
  output-dir: docs

website:
  title: "Michal Pawlowski"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/misza222
      - icon: twitter
        href: https://twitter.com/misza222
      - icon: linkedin
        href: https://linkedin.com/in/misza/
format:
  html:
    theme: cosmo
    css: styles.css