project:
  type: website
  output-dir: docs

website:
  title: "Michał Pawłowski"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/misza222
      - icon: twitter
        href: https://twitter.com/misza222
      - icon: linkedin
        href: https://linkedin.com/in/misza/
format:
  html:
    theme: litera
    css: styles.css

comments: 
  utterances: 
    repo:  misza222/misza222.github.com